CREATE DATABASE WEBSITE;
CREATE TABLE DOCTOR(ID INT PRIMARY KEY NOT NULL,NAME VARCHAR(30) NOT NULL,SPECIALIZATION VARCHAR(30) NOT NULL);
CREATE TABLE APPOINTMENTS(APMNT_N0 INT PRIMARY KEY NOT NULL,PATIENT_NAME VARCHAR(30) NOT NULL,DATE_ DATE NOT NULL,TIME_ TIME NOT NULL);
CREATE TABLE PATIENT(NAME VARCHAR(30) NOT NULL,AGE INT NOT NULL,SEX VARCHAR(1) NOT NULL,DATE_ DATE NOT NULL);
CREATE TABLE PATIENT_REVIEWS(NAME VARCHAR(30) NOT NULL,APMNT_NO INT NOT NULL,DOCTOR_ID INT NOT NULL,REVIEW VARCHAR(100) NOT NULL);